### ISSUE TITLE
Using ammoo.Connection outside Context Manager

### ISSUE THREAD

**Issue by jakubczaplicki** [mwfrojdman/ammoo#4]
Currently `ammoo.Connection` is a Context Manager. Is there a plan to refactor it so that we can pass `connection` down to a function ? In other words to make this work:
```
connection = await connect()  # works, but...
connection.channel()  # raises an exception because connection isn't entered
```
(example from https://ammoo.readthedocs.io/en/latest/api.html#ammoo.connect )

**Comment by mwfrojdman** [comment]
Hi,
you need to use `async with` for the connection. It's a context manager because most things in AMQP that you close/cancel (connection, channel, consumer) needs back-and-forth communication with the server and the context manager's __aexit__ allows to do that.

The examples section of the docs have better howtos: https://ammoo.readthedocs.io/en/latest/examples/connect.html. The API doc is lower level and is good for eg. checking what arguments a method accepts

**Comment by jakubczaplicki** [comment]
Sorry for late reply. I am aware of how the code should be used as it is now.
However what I'd like to be able to do is to write a class that would hold the `connection` for me.

Something like

```
class AIOAMQPPublisher:
    def __init__(self, exchange, routing_key, loop=None):
        self.exchange = exchange
        self.routing_key = routing_key
        self.connection = None
        self.channel = None
        self.loop = loop

    async def open_connection(self, amqp_url, loop=None):
        self.connection = await connect(amqp_url, loop=loop)

    async def publish(self, msg: dict):
        async with self.connection.channel() as channel:
            await channel.publish(self.exchange, self.routing_key, json=msg)
 
```

**Comment by mwfrojdman** [comment]
Hi,
in order to wrap a context manager (regular or asynchronous), you need to make the wrapping class a context manager as well.

Basically you need to define `async def __aenter__(self)`, call `await self.connection.__aenter__()` from there and return self. And have a `async def __aexit__(self, typ, value, traceback)` where you `await self.connection.__aexit__(typ, value, traceback)`. And if you have some other cleanup that you want to do, add that to the __aexit__ method as well.

Python 3.7 will have https://docs.python.org/3.7/library/contextlib.html#contextlib.asynccontextmanager to facilitate that, but until it's released one has to do that oneself. The idea is the same as with non-asynchronous context managers (ie. def __enter__ and def __exit__ instead of async defs).

**Comment by mwfrojdman** [comment]
Another option, avoiding a context manager, is to pass an open connection to your publisher class and use within the context. Something like this:

```
async with await connect(amqp_url) as connection:
    publisher = AIOAMQPPublisher(connection, ...)
    await publisher.publish(msg)
```
